sources:
  - name: 'PIZZA_DATA'
    database: 'HACKATHON' 
    schema: 'DATA_SAMPLE'
    tables:
      - name: "PIZZA_CUSTOMERS"
      - name: "PIZZA_ORDERS"
      - name: "PIZZA_ORDER_ITEMS"
      - name: "PIZZA_ORDER_ITEM_TOPPINGS"

models:
  - name: orders
    config:
        materialized: table
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: customers
    config:
        materialized: table
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: order_items
    config:
        materialized: table
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: product_image
        tests:
          - procento_vyplneni

  - name: toppings
    config:
        materialized: table
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null  

        tags: [id_is_primary_key]

